apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: nodejs-app-multi-components-repo
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/hacdev/gwotopiv-tenant/multi-components-repotest-app-170185006/nodejs-app-multi-components-repo@sha256:503c3f134a2f54e83d89806b548a05cc6caf883b7a54875f120aca475ee2166a
        name: my-nodejs
        resources: {}
status: {}
